# -*- coding: utf-8 -*-
"""Prompts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXubV0Os3neoke55CJlUyF4d50TG_i42
"""

from langchain_core.prompts import ChatPromptTemplate

# -------------------------------
# Ask AI Prompt
# -------------------------------

ASK_AI_PROMPT = ChatPromptTemplate.from_template("""
You are an experienced Product Manager.

Below are customer reviews.

{context}

Question:
{question}

Answer ONLY using the reviews provided.

Your answer should include:

- Summary
- Key Insights
- Recommendation
""")


# -------------------------------
# Sprint Summary Prompt
# -------------------------------

SPRINT_PROMPT = ChatPromptTemplate.from_template("""
You are a Senior Product Manager.

Customer Reviews:

{context}

Prepare a Sprint Summary.

Include:

## Executive Summary

## Top Customer Issues

## Sprint Goals

## Risks

## Recommendations

Base your answer ONLY on the reviews.
""")


# -------------------------------
# Jira Prompt
# -------------------------------

JIRA_PROMPT = ChatPromptTemplate.from_template("""
You are an experienced Product Manager.

Customer Reviews:

{context}

Generate ONE professional Jira ticket.

Include:

## Issue Type

## Summary

## Description

## Priority

## Severity

## Labels

## Acceptance Criteria

## Definition of Done
""")


# -------------------------------
# Trending Topics Prompt
# -------------------------------

TOPIC_PROMPT = ChatPromptTemplate.from_template("""
You are a Product Manager.

Below are customer reviews.

{reviews}

Identify the 8 most common discussion topics.

Return ONLY the topic names as a numbered list.
""")


# -------------------------------
# Issue Matrix Prompt
# -------------------------------

ISSUE_MATRIX_PROMPT = ChatPromptTemplate.from_template("""
You are a Senior Product Manager.

Analyze ALL customer reviews.

Customer Reviews:

{reviews}

Return the result as a markdown table.

Columns

| Rank | Issue | Frequency | Business Impact | Priority |

Priority should be one of

🔴 Critical

🟠 High

🟡 Medium

🟢 Low

Do NOT invent issues.

Only use issues found in the reviews.
""")