# -*- coding: utf-8 -*-
"""rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIxcaM0phjhv8NEsNMv6OLiInfz-leRt
"""

import os
import pandas as pd

from langchain_core.documents import Document
from langchain_core.output_parsers import StrOutputParser

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_groq import ChatGroq

from prompts import (
    ASK_AI_PROMPT,
    SPRINT_PROMPT,
    JIRA_PROMPT,
    TOPIC_PROMPT,
    ISSUE_MATRIX_PROMPT
)

# -------------------------------------
# Configuration
# -------------------------------------

CSV_PATH = "chatgpt_reviews_cleaned.csv"
VECTOR_DB_PATH = "chatgpt_review_index"

# -------------------------------------
# Load API Key
# -------------------------------------

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

if not GROQ_API_KEY:
    raise ValueError(
        "GROQ_API_KEY not found. Add it to Hugging Face Secrets."
    )

# -------------------------------------
# Initialize LLM
# -------------------------------------

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    groq_api_key=GROQ_API_KEY,
    temperature=0
)

parser = StrOutputParser()

# -------------------------------------
# Load Dataset
# -------------------------------------

df = pd.read_csv(CSV_PATH)

documents = []

for _, row in df.iterrows():

    documents.append(
        Document(
            page_content=str(row["content"]),
            metadata={
                "user": str(row["userName"]),
                "rating": int(row["score"]),
                "likes": int(row["thumbsUpCount"]),
                "date": str(row["at"]),
                "version": str(row["reviewCreatedVersion"])
            }
        )
    )

# -------------------------------------
# Embeddings
# -------------------------------------

embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-small-en-v1.5"
)

# -------------------------------------
# Load Existing FAISS
# -------------------------------------

db = FAISS.load_local(
    VECTOR_DB_PATH,
    embeddings,
    allow_dangerous_deserialization=True
)

retriever = db.as_retriever(
    search_kwargs={"k": 5}
)

# -------------------------------------
# Helper Function
# -------------------------------------

def get_context(query):

    docs = retriever.invoke(query)

    context = ""

    for i, doc in enumerate(docs, start=1):

        context += f"""

Review {i}

Rating : {doc.metadata['rating']}

Likes : {doc.metadata['likes']}

Version : {doc.metadata['version']}

Review

{doc.page_content}

-----------------------------------

"""

    return context

# -------------------------------------
# Chains
# -------------------------------------

ask_chain = ASK_AI_PROMPT | llm | parser

sprint_chain = SPRINT_PROMPT | llm | parser

jira_chain = JIRA_PROMPT | llm | parser

topic_chain = TOPIC_PROMPT | llm | parser

issue_chain = ISSUE_MATRIX_PROMPT | llm | parser

# -------------------------------------
# Dashboard Content
# -------------------------------------

TOPIC_FILE = "topics.md"
ISSUE_FILE = "issue_matrix.md"

if os.path.exists(TOPIC_FILE) and os.path.exists(ISSUE_FILE):

    with open(TOPIC_FILE, "r", encoding="utf-8") as f:
        TOPICS = f.read()

    with open(ISSUE_FILE, "r", encoding="utf-8") as f:
        ISSUE_MATRIX = f.read()

else:

    all_reviews = "\n\n".join(
        [doc.page_content for doc in documents]
    )

    TOPICS = topic_chain.invoke({
        "reviews": all_reviews
    })

    ISSUE_MATRIX = issue_chain.invoke({
        "reviews": all_reviews
    })

    with open(TOPIC_FILE, "w", encoding="utf-8") as f:
        f.write(TOPICS)

    with open(ISSUE_FILE, "w", encoding="utf-8") as f:
        f.write(ISSUE_MATRIX)

# -------------------------------------
# AI Functions
# -------------------------------------

def ask_ai(question):

    context = get_context(question)

    return ask_chain.invoke({

        "context": context,

        "question": question

    })


def generate_sprint_summary(query):

    context = get_context(query)

    return sprint_chain.invoke({

        "context": context

    })


def generate_jira_ticket(query):

    context = get_context(query)

    return jira_chain.invoke({

        "context": context

    })
